name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: ['latest', '1.8', '1.7', '1.6']

    container:
      image: elixir:${{matrix.elixir}}

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile
    - name: Run Tests
      run: mix test
